### PR TITLE
test on 3km

### PR DESCRIPTION
**Pull request by wangzhao0217**

### CODE REVIEW

**Review by Robinlovelace — COMMENTED** [review]
Thanks for the PR Zhao, I'll take a look now.

**Comment by Robinlovelace** [comment]
Currently checking out the code with 

```
git checkout -b wangzhao0217-520-add-arguments-to-rnet_merge-preventing-sideroads-getting-values-of-main-roads 520-add-arguments-to-rnet_merge-preventing-sideroads-getting-values-of-main-roads
git pull https://github.com/wangzhao0217/stplanr.git 520-add-arguments-to-rnet_merge-preventing-sideroads-getting-values-of-main-roads
```

**Comment by wangzhao0217** [comment]
Hi Robin,

I am running the code now, it will take times, if you notice any issues pls let me know.

**Comment by Robinlovelace** [comment]
Thanks Zhao, I've taken a look and the results look fine, but the high values on sideroads are still there, as shown below from the output of the new vignette:

image

**Comment by Robinlovelace** [comment]
Great, thanks. Keep up the good work. 

I can see that https://github.com/wangzhao0217/stplanr/blob/520-add-arguments-to-rnet_merge-preventing-sideroads-getting-values-of-main-roads/vignettes/merging-route-networks%203km.Rmd 

is currently the same as https://github.com/ropensci/stplanr/blob/master/vignettes/merging-route-networks.Rmd

Feel free to tag me when you want me to take a look.

**Comment by Robinlovelace** [comment]
Note: I've now merged this PR https://github.com/ropensci/stplanr/pull/521

If you can fix the issues that cause GitHub Actions to fail that would be amazing :pray:

**Pull request closed without merging**
