### PR TITLE
Add more comprehensive example of SpatialLinesNetwork()

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
@richardellison the aim here is to show the user what is going on (partly for my own understanding).

This what I get - makes sense, going from point 1 to 50 on the map:

image

**Comment by Robinlovelace** [comment]
But this is what I get when I change line 60 to:

```r
#' from_id = 10
```

image

Not what I was expecting! Explanation of what's going on appreciated.

**Comment by richardellison** [comment]
I'm looking into this, taking a bit longer than I expected to track down. It seems the source of the problem is how the igraph nodes are linked back to specific coordinates which is resulting in problems in constructing the final line because in some cases coordinates need to be reversed and the incorrect node coordinates are resulting in this being done incorrectly.

**Comment by Robinlovelace** [comment]
Hmm yes igraph nodes seem non-trivial. Best of luck with it and let me know if there's anyway I can help. Sorry if I just opened a can of worms! (Heads up @edzer - any guidance welcome.)

**Pull request merged**
