### PR TITLE
Add save_raw functionality to route_cyclestreet

### PR DESCRIPTION
**Pull request by Robinlovelace**
I think we should additionally do this for the other routing functions so people can go back to the raw json files spat out by these things. Will put in a separate issue for splitting out the code used to interpret the json objects and look into the implications of this for the `line2route()` wrapper function.

Comments welcome.

### CODE REVIEW

**Comment by richardellison** [comment]
This was my original thinking behind having separate functions for retrieving the OSRM routes and converting these to SpatialLinesDataFrames. Perhaps one option would be to use three functions:

1. Function that calls the routing engine and returns a JSON object (in hindsight probably better than returning the json string).
2. Function that converts the JSON object into a Spatial* object.
3. A wrapper function that calls first 1. then 2. (and returns a Spatial* object).

If we keep the wrapper function as the same as the current name of the functions then any existing scripts will still work.

**Comment by Robinlovelace** [comment]
I completely agree with your 3 phase proposal. Further, I suggest that 1 and 2 are service specific (e.g. `route_cyclestreet` and `route_graphhopper` - could we make a copy of `viaroute` called `route_osrm` for consistency) and than 3 is generic - that's the purpose of `line2route` which is designed to take any routing fun. I would further suggest a 4th function:

- A function to batch *download* routes.

Sound good? How about `route_download(fun, lines, ...)` for that? What do you think about building on `line2route()` for 3)? Happy for you to work on any of that, I'm up for working on the batch downloading if you want but your input or function development would be very much appreciated.

**Comment by Robinlovelace** [comment]
Another thing: maybe `route_*` functions would be better if they also could take many OD pairs as inputs. Thoughts? Wouldn't be too hard to refactor them for that and I'm up for you giving that a bash - that way they'd be consistent with `viaroute()` which would be a good thing.

**Comment by richardellison** [comment]
I'm not sure we need a separate function to download many routes? It could just return a list if more than one OD pair is passed to the function (and this could then be used in the route_* functions. I agree that we may as well make the wrapper function for OSRM consistent with the others.

**Comment by Robinlovelace** [comment]
Agreed with your suggestion - 1, 2 and 3 should also work on many OD pairs so we don't need 4). I'm happy to try implementing it for `route_cyclestreet()`. The would you be happy to review and try creating implementations for graphhopper and osrm? Next on the API wish list for me: `route_otp()`

In terms of naming how's `call_cyclestreet` and `interpret_cyclestreet` for 1 and 2? Then I imagine 3 could be the wrapper function.

**Comment by richardellison** [comment]
Seems reasonable to me. I'll have a go soon and I'll update the OSRM functions to use the httr package when I do it.

**Comment by Robinlovelace** [comment]
Please can you review and merge if this is working - still many WIP things but there's also a bug fix that's got mixed up in there.

**Pull request merged**
