### PR TITLE
update changes to the graphhopper api

### PR DESCRIPTION
**Pull request by seanolondon**
I was getting this error: 
Error in obj$paths$points[[1]][[1]][, 1:2] : 
  incorrect number of dimensions

The points were the next line down so changing the first '1' to a '2' fixes this.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
It still seems to fail on my laptop. Please could you provide a reprex showing this works (may be an api key issue on my machine):

``` r

# Aim: test new update to route graphhopper
library(stplanr)
from <- c(-0.12, 51.5)
to <- c(-0.14, 51.5)
r1 <- route_graphhopper(from = from, to = to) # fail
#> Error in route_graphhopper(from = from, to = to): Unauthorized (HTTP 401).

route_g <- function(from, to, l = NULL, vehicle = "bike", silent = TRUE, pat = NULL, base_url = "https://graphhopper.com") {
  
  # Convert character strings to lon/lat if needs be
  coords <- od_coords(from, to, l)
  
  if (is.null(pat)) {
    pat <- api_pat("graphhopper")
  }
  
  httrmsg <- httr::modify_url(
    base_url,
    path = "/api/1/route",
    query = list(
      point = paste0(coords[1, c("fy", "fx")], collapse = ","),
      point = paste0(coords[1, c("ty", "tx")], collapse = ","),
      vehicle = vehicle,
      locale = "en-US",
      debug = "true",
      points_encoded = "false",
      key = pat
    )
  )
  if (silent == FALSE) {
    print(paste0("The request sent was: ", httrmsg))
  }
  httrreq <- httr::GET(httrmsg)
  httr::stop_for_status(httrreq)
  
  if (grepl("application/json", httrreq$headers$`content-type`) == FALSE) {
    stop("Error: Graphhopper did not return a valid result")
  }
  
  txt <- httr::content(httrreq, as = "text", encoding = "UTF-8")
  if (txt == "") {
    stop("Error: Graphhopper did not return a valid result")
  }
  
  obj <- jsonlite::fromJSON(txt)
  
  if (is.element("message", names(obj))) {
    if (grepl("Wrong credentials", obj$message) == TRUE) {
      stop("Invalid API key")
    }
  }
  route <- sp::SpatialLines(list(sp::Lines(list(sp::Line(obj$paths$points[[2]][[1]][, 1:2])), ID = "1")))
  
  climb <- NA # to set elev variable up
  
  # get elevation data if it was a bike trip
  if (vehicle == "bike") {
    change_elev <- obj$path$descend + obj$paths$ascend
  } else {
    change_elev <- NA
  }
  
  # Attribute data for the route
  df <- data.frame(
    time = obj$paths$time / (1000 * 60),
    dist = obj$paths$distance,
    change_elev = change_elev
  )
  
  route <- sp::SpatialLinesDataFrame(route, df)
  sp::proj4string(route) <- sp::CRS("+init=epsg:4326")
  route
}

r1 <- route_g(from = from, to = to)
#> Error in route_g(from = from, to = to): Unauthorized (HTTP 401).
```

<sup>Created on 2019-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by seanolondon** [comment]
Hi Robin,

I think it may be your API key, if I use the ‘pat’ parameter with my api key it works. See below

library(stplanr)

graphhopper_api_key <- #API KEY#

from <- c(-0.12, 51.5)
to <- c(-0.14, 51.5)
r1 <- route_graphhopper(from = from, to = to, pat = graphhopper_api_key) # function fails even with correct api key

route_g <- function(from, to, l = NULL, vehicle = "bike", silent = TRUE, pat = NULL, base_url = "https://graphhopper.com") {

  # Convert character strings to lon/lat if needs be
  coords <- od_coords(from, to, l)

  if (is.null(pat)) {
    pat <- api_pat("graphhopper")
  }

  httrmsg <- httr::modify_url(
    base_url,
    path = "/api/1/route",
    query = list(
      point = paste0(coords[1, c("fy", "fx")], collapse = ","),
      point = paste0(coords[1, c("ty", "tx")], collapse = ","),
      vehicle = vehicle,
      locale = "en-US",
      debug = "true",
      points_encoded = "false",
      key = pat
    )
  )
  if (silent == FALSE) {
    print(paste0("The request sent was: ", httrmsg))
  }
  httrreq <- httr::GET(httrmsg)
  httr::stop_for_status(httrreq)

  if (grepl("application/json", httrreq$headers$`content-type`) == FALSE) {
    stop("Error: Graphhopper did not return a valid result")
  }

  txt <- httr::content(httrreq, as = "text", encoding = "UTF-8")
  if (txt == "") {
    stop("Error: Graphhopper did not return a valid result")
  }

  obj <- jsonlite::fromJSON(txt)

  if (is.element("message", names(obj))) {
    if (grepl("Wrong credentials", obj$message) == TRUE) {
      stop("Invalid API key")
    }
  }
  route <- sp::SpatialLines(list(sp::Lines(list(sp::Line(obj$paths$points[[2]][[1]][, 1:2])), ID = "1")))

  climb <- NA # to set elev variable up

  # get elevation data if it was a bike trip
  if (vehicle == "bike") {
    change_elev <- obj$path$descend + obj$paths$ascend
  } else {
    change_elev <- NA
  }

  # Attribute data for the route
  df <- data.frame(
    time = obj$paths$time / (1000 * 60),
    dist = obj$paths$distance,
    change_elev = change_elev
  )

  route <- sp::SpatialLinesDataFrame(route, df)
  sp::proj4string(route) <- sp::CRS("+init=epsg:4326")
  route
}

r1 <- route_g(from = from, to = to, pat = graphhopper_api_key) #

r1

**Comment by Robinlovelace** [comment]
Confirmed - suggest trying reprex to show reproducible examples next time. Example below (with updated key):

``` r
library(stplanr)
    from <- c(-0.12, 51.5)
    to <- c(-0.14, 51.5)
    r1 <- route_graphhopper(from = from, to = to) # fail
#> Error in obj$paths$points[[1]][[1]][, 1:2]: incorrect number of dimensions
    #> Error in route_graphhopper(from = from, to = to): Unauthorized (HTTP 401).
    
    route_g <- function(from, to, l = NULL, vehicle = "bike", silent = TRUE, pat = NULL, base_url = "https://graphhopper.com") {
        
        # Convert character strings to lon/lat if needs be
        coords <- od_coords(from, to, l)
        
        if (is.null(pat)) {
            pat <- api_pat("graphhopper")
        }
        
        httrmsg <- httr::modify_url(
            base_url,
            path = "/api/1/route",
            query = list(
                point = paste0(coords[1, c("fy", "fx")], collapse = ","),
                point = paste0(coords[1, c("ty", "tx")], collapse = ","),
                vehicle = vehicle,
                locale = "en-US",
                debug = "true",
                points_encoded = "false",
                key = pat
            )
        )
        if (silent == FALSE) {
            print(paste0("The request sent was: ", httrmsg))
        }
        httrreq <- httr::GET(httrmsg)
        httr::stop_for_status(httrreq)
        
        if (grepl("application/json", httrreq$headers$`content-type`) == FALSE) {
            stop("Error: Graphhopper did not return a valid result")
        }
        
        txt <- httr::content(httrreq, as = "text", encoding = "UTF-8")
        if (txt == "") {
            stop("Error: Graphhopper did not return a valid result")
        }
        
        obj <- jsonlite::fromJSON(txt)
        
        if (is.element("message", names(obj))) {
            if (grepl("Wrong credentials", obj$message) == TRUE) {
                stop("Invalid API key")
            }
        }
        route <- sp::SpatialLines(list(sp::Lines(list(sp::Line(obj$paths$points[[2]][[1]][, 1:2])), ID = "1")))
        
        climb <- NA # to set elev variable up
        
        # get elevation data if it was a bike trip
        if (vehicle == "bike") {
            change_elev <- obj$path$descend + obj$paths$ascend
        } else {
            change_elev <- NA
        }
        
        # Attribute data for the route
        df <- data.frame(
            time = obj$paths$time / (1000 * 60),
            dist = obj$paths$distance,
            change_elev = change_elev
        )
        
        route <- sp::SpatialLinesDataFrame(route, df)
        sp::proj4string(route) <- sp::CRS("+init=epsg:4326")
        route
    }
    
    r1 <- route_g(from = from, to = to);r1;plot(r1)
#> class       : SpatialLinesDataFrame 
#> features    : 1 
#> extent      : -0.140081, -0.119311, 51.50001, 51.50132  (xmin, xmax, ymin, ymax)
#> coord. ref. : +init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 
#> variables   : 3
#> names       :             time,     dist,      change_elev 
#> value       : 7.42746666666667, 1599.452, 24.7479960918427
```



<sup>Created on 2019-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Robinlovelace** [comment]
Many thanks for the bug spot and fix btw, really helpful. Please put in a PR to the DESCRIPTION if you'd like to be listed as a contributor.

**Pull request merged**
