### PR TITLE
Add ability for overline to use grouping variables.

### PR DESCRIPTION
**Pull request by richardellison**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
This looks good, but can you provide an example in `@examples` to show what it does.

What about in the case when `byvars != NA`?

**Comment by richardellison** [comment]
I will try to come up with a simple example.

What I am doing is overlaying trips between bus stops with the number of passengers travelling between each pair of bus stops so I get how many people are travelling on a specific section of a bus route. In my case I am doing this for passengers who take a specific bus route (to see which services they are connecting to/from) and for that reason I want to keep the different bus routes separate even when they travel along the same road (the white line is the "reference" route):

busroutesmap

**Comment by Robinlovelace** [comment]
Very cool - so glad it's useful beyond the specific use case for which it was developed: that map looks great. Maybe the following code could form the basis of a simple example that uses this new functionality:

```r
library(stplanr)
routes_fast$group = rep(1:3, length.out = nrow(routes_fast))
rnet_grouped = overline(routes_fast, attrib = "length", byvars = "group")
```

(For some reason that code breaks using your update of the function - any ideas?)

**Comment by richardellison** [comment]
It seems I forgot to replace the column names I was using to test the function with the variable that was being passed to the function. I've fixed that now and added your example to the documentation.

**Pull request merged**
