### PR TITLE
Small change to sum_network_routes function

### PR DESCRIPTION
**Pull request by richardellison**
This PR speeds up calculating combinations of routes using a SpatialLinesNetwork. This is useful if you want to calculate all routes from a single origin to many destinations or many origins to the same set of destinations.

### CODE REVIEW

**Comment by richardellison** [comment]
Yes, that's true. The example is in the main SpatialLinesNetwork class rather than the individual functions. I'll add some simple examples.

**Comment by Robinlovelace** [comment]
Thanks

**Comment by richardellison** [comment]
I have added examples. They are derivatives of the main example for the class to keep things consistent.

**Comment by Robinlovelace** [comment]
Good plan to use existing data for examples - will greatly improve the ability of others to use those functions. I've updated the NEWS accordingly: https://github.com/ropensci/stplanr/commit/8b045f3f6ad70a448fd691733753505714f1ed35

**Pull request merged**
