### PR TITLE
Refactor overline ii

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
This looks great after adding some examples, great speed-up.

image

**Comment by Robinlovelace** [comment]
I think there is still an issue though: the method is now *too keen* to join up linestrings I think. The box in the example shown below is not 4 separate features as I think it should be, but a single geometry. Heads-up @mem48.

**Comment by Anyaoha** [comment]
Can this be used for optimization of route?


Sent from Yahoo Mail for iPhone


On Monday, February 11, 2019, 7:38 AM, Robin <notifications@github.com> wrote:


This looks great after adding some examples, great speed-up.

**Comment by Robinlovelace** [comment]
@mem48 a reproducible example of the issue is provided below:

``` r
devtools::install_github("ropensci/stplanr", "refactor-overlineII")
#> Skipping install of 'stplanr' from a github remote, the SHA1 (0038ca4c) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(stplanr)
sl = routes_fast_sf[!is.na(routes_fast_sf$length), ]
sl$bicycle = 1
system.time({rnet1 = overline2(sl, "bicycle")})
#> Loading required namespace: pbapply
#> 2019-02-11 15:46:34 constructing segments
#> 2019-02-11 15:46:34 transposing 'B to A' to 'A to B'
#> 2019-02-11 15:46:34 removing duplicates
#> 2019-02-11 15:46:34 restructuring attributes
#> 2019-02-11 15:46:34 building geometry
#> 2019-02-11 15:46:34 simplifying geometry
#> 2019-02-11 15:46:34 rejoining segments into linestrings
#>    user  system elapsed 
#>   0.172   0.004   0.176
system.time({rnet2 = overline2(sl, "bicycle", ncores = 4)})
#> 2019-02-11 15:46:34 constructing segments
#> 2019-02-11 15:46:34 transposing 'B to A' to 'A to B'
#> 2019-02-11 15:46:34 removing duplicates
#> 2019-02-11 15:46:34 restructuring attributes
#> 2019-02-11 15:46:34 building geometry
#> 2019-02-11 15:46:34 simplifying geometry
#> 2019-02-11 15:46:34 rejoining segments into linestrings
#>    user  system elapsed 
#>   0.136   0.000   0.136
plot(rnet1, lwd = rnet1$bicycle)
```



``` r
nrow(rnet1)
#> [1] 70
rnet1_2 = rnet1[rnet1$bicycle == 2, ]
plot(rnet1_2)
```



``` r
plot(rnet1_2[7, ])
```



<sup>Created on 2019-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Pull request merged**
