### PR TITLE
Overline doc

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @mem48 this is work in progress.

**Comment by mem48** [comment]
Looks ok, but hard to tell with all the changes, if the tests pass I suggest merge and the do a human check of the docs to make sure.

**Comment by Robinlovelace** [comment]
Heads-up @mem48 here is the updated merged documentation: https://docs.ropensci.org/stplanr/reference/overline2.html

**Comment by mem48** [comment]
The second paragraph is confusing as it says it is a replacement to itself

**Comment by mem48** [comment]
Lots of warnings in the examples

**Comment by Robinlovelace** [comment]
That's will be fixed when this is fixed: https://github.com/ropensci/stplanr/issues/364

**Pull request merged**
