### PR TITLE
Initial fixes to osrm functions.

### PR DESCRIPTION
**Pull request by richardellison**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Still doesn't seem to work, e.g.:
```
exroutes <- viaroute(50, 0, 51, 1)
exroutes
[1] ""
```

The next line in the example errors for me on your branch.

**Comment by richardellison** [comment]
I'm seeing the same thing but doesn't seem to be an issue with the function. If I run the constructed query in a browser I need to refresh a few times until it returns a result. Maybe there is something going on with the OSRM server?

**Comment by richardellison** [comment]
I have added a check to make sure that the result of viaroute is not empty and if it is to give you an error. Now that I have added it though, I can't reproduce the problem.

**Comment by Robinlovelace** [comment]
Agreed - working now, not sure what was causing that. Cheers.

**Pull request merged**
