### PR TITLE
Update NEWS + tweak e.g. for overline

### PR DESCRIPTION
**Pull request by Robinlovelace**
NB: we need to make more news updates before the next release - can you remember what's changed @richardellison?

### CODE REVIEW

**Comment by richardellison** [comment]
Some changes that come to mind:

* OSRM functions now support OSRM API v5
* Updates to od2line
* Improvements to google functions

**Comment by Robinlovelace** [comment]
OK @richardellison I think that's everything now - `dist_google()` was in the previous release so not in news. Ready for me to build and release?

**Comment by richardellison** [comment]
I think we're ready to go now. Just need to update the DESCRIPTION with the date first.

**Comment by Robinlovelace** [comment]
Great - job done releasing it now.

**Pull request merged**
