### PR TITLE
one mis-placed line wreaks havoc!

### PR DESCRIPTION
**Pull request by mpadge**
The man entries were all mucked up because the `osm_net_example` had `@rdname route_dodgr`, so all references to that were re-mapped to the roxygen stuff for `osm_net_example`. Check, for example, the [website for `route_dodgr`](https://ropensci.github.io/stplanr/reference/route_dodgr.html) which starts, "Example of OpenStreetMap road network". This should fix everything up.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Hey Mark, just saw this, thanks loads for the update. Unfortunately it seems there's a conflict somewhere and I've just resubmitted to CRAN before seeing this. If it doesn't go up, I can merge this and submit 0.2.8-1 or just 0.2.9. Thoughts?

**Comment by Robinlovelace** [comment]
But yeah I totally see your point about https://ropensci.github.io/stplanr/reference/route_dodgr.html

**Comment by Robinlovelace** [comment]
Well, that was easier than expected.

**Comment by Robinlovelace** [comment]
FYI for anyone seeing merge conflicts e.g. @mem48 this is how to pull upstream commits:

```
   git remote add mpadge git@github.com:mpadge/stplanr
   git fetch mpadge
   git merge mpadge/master
  # git mergetool if needed
   git push
```

**Comment by mpadge** [comment]
Sorry, those conflicts are probably my fault, even though there was nothing in them. Related to the quashed commits listed above. I probably should have `git push --force` to my fork before doing this. Thanks!

**Comment by Robinlovelace** [comment]
Heads-up @mpadge your fix broke Travis: https://travis-ci.org/ropensci/stplanr/builds/509945193#L1544

**Comment by Robinlovelace** [comment]
Update: `devtools::document()` fixes it, so that was a misplaced nudge. Apologies. And thanks.

**Pull request merged**
