### PR TITLE
Add bidirectional argument to line_bearing()

### PR DESCRIPTION
**Pull request by Robinlovelace**
If it's TRUE, the results apply in either direction

### CODE REVIEW

**Comment by richardellison** [comment]
The Travis-CI build is failing. Looks like some of the arguments have not been documented properly (angle in angle_diff() for instance). Should just require correcting the documentation and then re-building.

**Comment by Robinlovelace** [comment]
Sure, will take a look.

**Comment by richardellison** [comment]
Still failing but it looks like all that is needed is to run roxygen2 to rebuild the documentation. I'll merge and then rebuild and put in a new PR to see if that works.

**Comment by Robinlovelace** [comment]
Thanks for the fix - I made the commit on a computer that lacked **roxygen2** but will defo re-document in future. Cheers!

**Pull request merged**
