### PR TITLE
Addition of tolerance parameter to SpatialLinesNetwork

### PR DESCRIPTION
**Pull request by richardellison**
This PR is to add a tolerance parameter when creating a SpatialLinesNetwork. This allows disconnected lines to be "connected" for the purposes of routing.

### CODE REVIEW

**Comment by fiftysevendegreesofrad** [comment]
Do you really want to do this when other tools exist for fixing networks e.g. v.clean in GRASS? If you follow a 'small tools' philosophy do your fixing elsewhere and feed stlplanr with clean network data. 

(I *think* v.clean can snap endpoints only to a tolerance though you'll have to check - I use sDNA prepare for this purpose though that isn't open source just yet). my notes on network cleaning http://www.cardiff.ac.uk/sdna/wp-content/downloads/documentation/manual/sDNA_manual_v3_4_5/network_preparation.html

**Comment by Robinlovelace** [comment]
Many thanks for this input Crispin, v.useful. In some ways the purpose of the package is to make existing tools more accessible to transport researchers who have limited experience of command line GIS (most I think) so providing higher level wrappers to stuff like v.clean could be a partial solution (e.g. via the **rgrass** package https://cran.r-project.org/package=rgrass7 ) but of course that would be another massive dependency that I doubt we'd want to add ATM. 

The sDNA manual's section on network preparation is really useful, and not something we've thought about much. Great to have your input.

**Comment by richardellison** [comment]
I agree Crispin that it really isn't necessary for stplanr to include a full suite of tools to fix networks. There are better places for those sorts of tools. My view is that if it is something small (likely allowing a tolerance) then having it in stplanr is useful as it makes for one less step when importing data. I completely agree that if a network needs more substantial fixing then that isn't really in scope.

@Robinlovelace If we end up thinking this is necessary, then I would think it would probably be better to have another package to contain functions that require these additional dependencies if people want to use them (similar to how tmap now has tmaptools).

**Comment by Robinlovelace** [comment]
Agreed - stplanr already has quite a broad remit: a toolkit for transport planning with an emphasis on spatial transport data, so unwise to dilute it further to try to be all things including a network processing package.

**Pull request merged**
