### PR TITLE
Shorten function names and fix viaroute2sldf

### PR DESCRIPTION
**Pull request by richardellison**
Shorten function names and fix viaroute2sldf to properly convert from factor to numeric after switch to jsonlite::fromJSON.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Looks good. I don't see the fix to viaroute2sldf here though, only changed function names...

**Comment by richardellison** [comment]
Fixes are lines 95-99 and 165-169 in osrmfunctions.R

**Comment by Robinlovelace** [comment]
Ah yes, I see the `as.numeric` in there - was looking for single liners!

Thanks

**Comment by Robinlovelace** [comment]
`as.character` rather, to prevent the factor id being used.

**Pull request merged**
