### PR TITLE
Improvements to overline2

### PR DESCRIPTION
**Pull request by mem48**
Overline2 function has the following improvements:

- Improved Docs

- Faster

- Less Memory Usage

Profile for 500 lines from the pct schools dataset in london

```
profile <- bench::mark(check = FALSE,
            r1 = stplanr::overline(sl = rf, attrib = c("bicycle","govtarget_slc","dutch_slc")),
            r2 = stplanr::overline2(x = rf, attrib = c("bicycle","govtarget_slc","dutch_slc")),
            r3 = overline3(x = rf, attrib = c("bicycle","govtarget_slc","dutch_slc"))
)
profile[,c(1,7,10)]
```
r1           104.1MB      1.09m
r2            74.8MB     16.54s
r3            67.5MB      9.08s

Note that results for r2 and r3 are not identical the row order is different so:

```
# Check Identical
r2$geometry <- sf::st_as_text(r2$geometry)
r3$geometry <- sf::st_as_text(r3$geometry)
r2 <- as.data.frame(r2)
r3 <- as.data.frame(r3)
r2 <- r2[order(r2$geometry), ]
r3 <- r3[order(r3$geometry), ]
rownames(r2) <- 1:nrow(r2)
rownames(r3) <- 1:nrow(r3)
identical(r2, r3) # TRUE
```

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Not passing tests: https://travis-ci.org/ropensci/stplanr/builds/521286232#L8985

**Comment by mem48** [comment]
This is a problem with dplyr::group_by when you don't quote column names

`c3 <- dplyr::group_by(c3, X1, Y1, X2, Y2)`

I don't know how to fix this, any suggestions?

**Comment by Robinlovelace** [comment]
Yes I know. It's like this: 

https://github.com/ropensci/stplanr/blob/ad643338ae1eecb31bc3de87fd478b1e9c4203cb/R/stplanr-package.R#L41

Replacing that with:

```
utils::globalVariables(c(".", "n", "matchingID", "X1", "Y1", "X2", "Y2"))

```

Should allow the tests to pass.

**Comment by mem48** [comment]
Thanks, pushed fix waiting for Travis

**Comment by mem48** [comment]
I made one more tweak, that reduces memory usage by another 4%

**Comment by mem48** [comment]
speeds are now for 500 lines

1 overline               274MB      4.03m
2 overline2             194MB     11.65s
3 overline2_new     306MB      6.98s

I raised the regionalization limit to 1e6, as it uses more memory but is faster on small datasets, on a larger dataset of 37,000 lines.

1 overline2          537.32MB      22.7s
2 overline2               1.16GB      13.8s

**Comment by Robinlovelace** [comment]
Great to see the checks passing. Good to see the speed-up too. Many thanks!

**Pull request merged**
