### PR TITLE
Revert dodgr removal

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @mpadge looking to re-add `dodgr` with this PR.

**Comment by mpadge** [comment]
no, don't. It got archived again yesterday, partly due to errors that have nothing to do with the package itself. I'll get it back on this coming week, and let you know here. Please wait until then. Sorry for any inconvenience

**Comment by Robinlovelace** [comment]
OK thanks @mpadge I've converted it to a draft PR for now.

**Comment by Robinlovelace** [comment]
Re-opening. Good to go from your perspective @mpadge ?

**Comment by mpadge** [comment]
CRAN checks are [all good](https://cran.r-project.org/web/checks/check_results_dodgr.html), so should be smooth sailing from here. The problem was RcppParallel, which had an unresolvable memory leak from a bundled library, and that memory leak prevented me being able to locally reproduce the CRAN results, so i could never find any bugs. RcppParallel have now ditched that library in favour of a non-:bug: one, which finally enabled me to locally reproduce CRAN problems, and thus finally find and fix everything. And it turn out that I had a tiny :bug: that did require fixing, and now has been. Phew. Again: sorry for inconvenience. Ought not be a reproducible practice :smile:

**Comment by Robinlovelace** [comment]
Awesome! Will merge it in!

**Pull request merged**
