### PR TITLE
More changes for OSRM v5 API

### PR DESCRIPTION
**Pull request by richardellison**
Additional changes to the OSRM functions to accommodate API v5 (see #72). Also fixes some issues with the nearest_osm function for API v4 where the function did not accept vectors/data.frame with coordinates as specified in the documentation.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Great to see this include support for both v4 and v5 api, and the seemingly new `profile` argument. Seems to be failing on CI though - any ideas why? Will give it a test and aim to add some examples that use these new parameters.

**Comment by richardellison** [comment]
I forgot to add data.table to the DESCRIPTION and NAMESPACE files so it was failing because it couldn't find the rbindlist function. Fixed now so this build should (hopefully!) pass.

**Comment by Robinlovelace** [comment]
Hmm still seems to be failing but cannot see from the build report why...

**Comment by richardellison** [comment]
Seems I forgot to update the documentation for the table2matrix function in the last commit (the previous build passed). Should be fixed in the latest commit.

**Comment by richardellison** [comment]
The build has passed now.

**Pull request merged**
